server {

    listen 80;

    server_name exemplo.com www.exemplo.com;

    root /var/www/exemplo/public_html;

    index index.php index.html;

    access_log /var/log/nginx/exemplo_access.log;

    error_log /var/log/nginx/exemplo_error.log;

    client_max_body_size 100M;

    charset utf-8;

    location / {

        try_files $uri $uri/ /index.php?$args;

    }

    location ~ \.php$ {

        include fastcgi_params;

        fastcgi_pass unix:/run/php/php-fpm.sock;

        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg|woff|woff2)$ {

        expires 30d;

        access_log off;

    }

    location ~ /\. {

        deny all;

    }

}